### ISSUE TITLE
EdiText main and edit container styles

### ISSUE THREAD

**Issue by rajraj** [alioguzhan/react-editext#11]
Hi, Thanks for the library, works great.

Just a little thing if possible.
Is there any way to override the styles for the Main and Edit container styles. I would like to have the buttons displayed under the input box.

![image](https://user-images.githubusercontent.com/9442/58794475-2f141000-85f0-11e9-96a4-4205c3a23e72.png)

**Comment by alioguzhan** [comment]
Hi @rajraj,

Nice idea. I can implement this in a day or two. If you are in a hurry feel free to PR. I'll let you know once I release a new version!

**Comment by alioguzhan** [comment]
Hey @rajraj ,

I just released a new version with new props to override container classes. Please see [the related section](https://alioguzhan.github.io/react-editext/#custom-classes-for-containers)

Also, see the [bottom of the props section in README.md](https://github.com/alioguzhan/react-editext#props)

Let me know if you have any question or suggestion!

**Comment by rajraj** [comment]
@alioguzhan awesome thank you so much :clap: 

Do you have a Buy me a Coffee page or something?

**Comment by alioguzhan** [comment]
No, not at this moment. But thanks anyway! Closing the issue. Feel free to reach me for anything.
