### ISSUE TITLE
Recommended way to watch "onChange" event

### ISSUE THREAD

**Issue by johnnypea** [alioguzhan/react-editext#119]
**Is your feature request related to a problem? Please describe.**
I would like to watch user input as he types and give him instant feedback.

**Describe the solution you'd like**
A method to hook into "onChange" prop?

**Describe alternatives you've considered**
I gues I can implement "onChange" myself. Maybe I can use "inputProps"?

**Comment by alioguzhan** [comment]
Hey,

You can use `inputProps` for this. I created a sample sandbox:

https://codesandbox.io/s/nifty-leakey-qsde9

Can you please check this and tell me if this is what you need?

**Comment by johnnypea** [comment]
`onKeyUp`, even `onInput` works but why not `onChange`? It would be more convenient for me as I can change field value in any way, not just rely on key press. Thank you.

**Comment by alioguzhan** [comment]
Hmm. You are right, I believe. Let me check that why it is not working.

**Comment by alioguzhan** [comment]
Hey, Can you please install `react-editext` from latest branch:

```
yarn add react-editext#fix-onChange-handler
```

And please let me know if it is working as expected. You can see an example here:

https://deploy-preview-120--react-editext.netlify.app/#custom-props-for-input-element

**Comment by johnnypea** [comment]
It works nicely, thanks!

**Comment by alioguzhan** [comment]
Great. `v4.1.5` is released at npm. Please upgrade the package :) @johnnypea 

@all-contributors please add @johnnypea for bug report
