### ISSUE TITLE
Value does not update when props change

### ISSUE THREAD

**Issue by sesteva** [alioguzhan/react-editext#12]
Thank for creating this component!

**Describe the bug**
The value prop may change but the implementation does not take this into account.
A possibility is to implement willReceiveProps or getDerivedProps to update the state properly.

**To Reproduce**
Examples: applications where the text is not hardcoded but loaded on bootstrap. this is pretty common when doing internationalization.

**Expected behavior**
If props change the component should react accordingly.

**Comment by alioguzhan** [comment]
Thanks for this. If you don't mind can you create a codesandbox reproduces this behavior?

**Comment by alioguzhan** [comment]
Oh, I think I get you what you mean. Did you try to solve this by setting a key to `<EdiText` component:

```jsx
<EdiText
  key={this.props.user.pk}
  value={this.props.user.username}
  onChange={handleUsernameChange}
/>
```
With this approach, everytime `key` value is changed `EdiText` will be re-created. See [official docs page](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key) for this pattern.

Let me know if this helps you. Thanks.
