### ISSUE TITLE
Anyone had any luck automating click and edit using Spectron / Webdriver?

### ISSUE THREAD

**Issue by andrew-mclachlan** [alioguzhan/react-editext#125]
I've been trying to automate a click and edit using Spectron / Webdriver but I keep getting "element is not interact-able". Nor am I able to retrieve the value of an entry box. I've tried many XPath combinations to see if click or getValue would work on them, but no luck.

Has anyone managed to automate this and if so, do you have any examples, tips or tricks?

Thanks in advance!

**Comment by alioguzhan** [comment]
Hey, I never used Spectron so I don't have any idea atm. Can you provide a sample code to reproduce this so I can play with it to see what is wrong and what can be done? 

Thanks!

**Comment by andrew-mclachlan** [comment]
Thanks -

```
<div class="styles_Editext__main_container__2Y-IL sc-pIJJz kEDzdV">
   <div editext="view-container">
      <div id="id-of-cell-I-want-to-click" editext="view">199</div>
      <div class="styles_Editext__buttons_container__1kphL styles_Editext__buttons_after_aligned__1nlcG">
          <button type="button" editext="edit-button" class="styles_Editext__button__6H8n_ styles_Editext__edit_button__hthOZ"></button></div>
          </div>
</div>
```

I found that if I use the XPath selector below (-) to the div above, the click returned "element is not interactable". If it used an XPath from the top-down, then I was able to click the entrybox.

```
-      `//*[@id="id-of-cell-I-want-to-click"]/ancestor::div[2]`
+      `//*[@id="some-table-containing-editext"]/div[2]/div[2]/div/div/div[${index}]/div[5]/div`
```

I needed to click the top div in order for it to work. 

I'm now trying to get the value (199) using an XPath selector but so far, I get null.

**Comment by andrew-mclachlan** [comment]
Unfortunately, I now get an element not in correct state when trying to set the value/text after the click.

Curious if anyone has automated the click, get, and set of this wonderful edit box.

**Comment by alioguzhan** [comment]
OK, I will install webdriver and try to achieve what you are trying to do. I ll let you know once I find something useful.

**Comment by alioguzhan** [comment]
I created a temporary directory. And inside of it, I installed below packages:

```
yarn add -D @wdio/local-runner chromedriver wdio-chromedriver-service
```

Then created a file named `editext.js`:

```js
const { remote } = require('webdriverio');

const data = {
    URL: 'https://alioguzhan.github.io/react-editext/',
    // URL: 'http://localhost:3001/',
    newValue: 'THIS IS NEW INPUT VALUE',
    xpath: {
        divText: `//body//div[@id='root']//div[@editext='view']`, // OR, //body//div[@id='root']//div[@id='my-custom-view-id'] BOTH WORKS
        editButton: `//body//div[@id='root']//button[@editext='edit-button']`,
        input: `//body//div[@id='root']//input[@editext='input']`,
        saveButton: `//body//div[@id='root']//button[@editext='save-button']`
    },
    attr: {
        divText: '[editext=view]',
        editButton: '[editext=edit-button]',
        input: '[editext=input]',
        saveButton: '[editext=save-button]'
    }
};

(async () => {
    console.log('STARTING TO TEST REACT EDITEXT....')
    const browser = await remote({
        capabilities: {
            browserName: 'chrome',
        },
        logLevel: 'warn'
    })
    await browser.url(data.URL)
    const divText = await browser.$(data.xpath.divText) // OR, data.attr.divText
    console.log('editext value in read mode: ', await divText.getText())

    const editButton = await browser.$(data.xpath.editButton) // OR, data.attr.editButton
    await editButton.click()
    
    const input = await browser.$(data.xpath.input) // OR, data.attr.input
    console.log('input value in edit mode (before): ', await input.getValue())
    
    console.log('setting new value...')
    
    await input.setValue(data.newValue)
    console.log('input value in edit mode: ', await input.getValue())

    const saveButton = await browser.$(data.xpath.saveButton); // OR, data.attr.saveButton
    await saveButton.click()
    console.log('saved new value.')
    console.log('DONE.')
})()
```

Then run this command:

``` node editext.js```

All seem working without any error. I checked both with CSS selectors and XPath selectors. Can you please check this? Or you are having a problem because of something else?

Thanks.

**Comment by andrew-mclachlan** [comment]
This is awesome! Thanks. I'll test it out.
