### ISSUE TITLE
On click of edit button check flag value and then enter in edit mode

### ISSUE THREAD

**Issue by shubh057** [alioguzhan/react-editext#127]
Can we do something like if any user clicks on edit button then maybe with the use of ```onEditingStart``` function I can check if flag value is set to true then only enter in edit mode otherwise show alert box with some message and keep the div only in view mode?

Thanks in advance!

**Comment by alioguzhan** [comment]
Hey, so you want to listen if a user clicks on the `edit button`, BUT instead of enabling the edit mode you want to check a condition. If condition passes, the user can enter into the `edit mode`. If not, you will prevent the user and show  a alert box. Is this is what you need here?

**Comment by ss62171** [comment]
@alioguzhan yes.

Thanks for your response.

**Comment by shubh057** [comment]
@alioguzhan yes.
Thanks for your response

**Comment by alioguzhan** [comment]
Hey, I added a new prop `canEdit`. Can you please check deploy preview page for that feature:

https://deploy-preview-128--react-editext.netlify.app/#conditioanl-editing

Tell me if this is what you need.

**Comment by shubh057** [comment]
Hey, I exactly needed this. I tried using this but it's not working. Can you share a working code on codepen?
Thanks,

**Comment by alioguzhan** [comment]
I just published a new version `4.2.0` to npm. Can you please upgrade the `react-editext` on your local and tell me if everything is OK? Thanks.

**Comment by shubh057** [comment]
Yes, working.
Thanks a lot.

**Comment by alioguzhan** [comment]
@all-contributors please add @shubh057 for ideas
