### ISSUE TITLE
validation prop: failed to validate when use with async and await

### ISSUE THREAD

**Issue by sanjain-progress** [alioguzhan/react-editext#152]
**Describe the bug**

I am trying to do the validation from the API call for this using `validation` prop.  And for this, invoking the function  using async and await. Validation never through any error

**Expected behavior**

```
// Originally, I want to make an API call. here for the simplicity returning false
 const updateCardName = async (val) => {
    // await axios.put(`folders/${item.id}`, { name })
    return false;
  };
```

```
<EdiText
          submitOnEnter
          type="text"
          value={cardName}
          // validation={(val) => updateCardName(val)} // this is working as expected
          validation={async (val) => {
            await updateCardName(val);
          }} // this is not working, trying to validate thorugh API
          validationMessage="Please change the name"
          cancelOnEscape
          onSave={() => {}}
        />
```

**CodeSandbox URL** Your CodeSandbox URL.

https://codesandbox.io/s/objective-bush-sno01b?file=/src/index.js

**Comment by alioguzhan** [comment]
Hi, thanks for reporting this. I will look into it. Meanwhile, feel free to create a PR.

**Comment by alioguzhan** [comment]
Hi, can you please install `EdiText` from the recent branch and see if it is working now:

```
yarn add https://github.com/alioguzhan/react-editext#alioguzhan/issue152
``` 

And you can try the validation function with something like this:

```ts
 async function validate(v: string) {
    const resp = await fetch(`https://jsonplaceholder.typicode.com/todos/1`);
    const data = await resp.json();
    console.log(data);
    return data.id > 1; // change > to === to make it valid
}
```

If it is working I can send a new release.

**Comment by sanjain-progress** [comment]
Hey @alioguzhan,

Thanks for making the time to fix this issue. 

I tried this in my local, Use the same [code](https://github.com/sanjain-progress/react-editext-issues152-/blob/main/src/App.js) which I did in CodeSandbox.
This time it is always throwing the error. 

You can check my code here: https://github.com/sanjain-progress/react-editext-issues152-

On the other side, I try to update the dependency at CodeSandbox via this 
`yarn add https://github.com/alioguzhan/react-editext#alioguzhan/issue152`, Seems like this is not supported by CodeSandbox

**Comment by alioguzhan** [comment]
Hi @sanjain-progress ,

`validation` prop should a take function that returns a `boolean` or `Promise<boolean>`. In your example, you are just calling `updateCardName(val)` with await. But that function does not return anything. Try one of these and let me know if it is working:

Option 1:
```jsx
validation={async (val) => await updateCardName(val)}
```

Option 2:
```jsx
validation={async (val) => {
  return await updateCardName(val);
}}
```

Option 3:

```jsx
validation={updateCardName}
```

**Comment by sanjain-progress** [comment]
@alioguzhan 
Thanks for pointing this out. It works perfectly.

You can close this issue and release a new version.

**Comment by alioguzhan** [comment]
@all-contributors please add @sanjain-progress for bug fix
