### ISSUE TITLE
validation not fire on type textarea / dynamically controlled save button 

### ISSUE THREAD

**Issue by spostad7** [alioguzhan/react-editext#159]
**Describe the bug**
The component doesn't follow validation rule on type textarea mode

**Expected behavior**
Expected to behave exactly like other types

here's my code so far, it's simple to test this:

```javascript
<EdiText
	type="textarea"
	value={
		state.companyOverviewDescription ||
		'------'
	}
	validation={(val) =>
		val.length < descriptionLimit
	}
	validationMessage={
		t('validation.max', {
			count: descriptionLimit
		}) as string
	}
	onSave={(val) =>
		handleUpdate({
			companyOverviewDescription: val
		})
	}
/>
```

**Comment by spostad7** [comment]
as I found out, this was happened when we have controlled save/edit button and it just only apply if the Enter key pressed. otherwise it won't trigger validation rule

**Comment by alioguzhan** [comment]
React Editext does not support controlled actions. The only place that validation happens is the **internal save button's onSave handler**. You are trying to trigger save and edit actions from an external component that is not supported. 

I designed this component for simple use cases like inline editing for tables or forms. You are trying to derive something more advanced than its capabilities. 

What you are trying to achieve is technically possible, but not with the current version. I am planning a rewrite for this in a near future. I am going to think about this.
