### ISSUE TITLE
Allow to remove buttons

### ISSUE THREAD

**Issue by anz000** [alioguzhan/react-editext#36]
I like the `editOnViewClick` which allows the text to be editable on click. 

I want to remove all the buttons altogether, and.
 - Start editing on click.
 - call onSave() if the the user moves away from the text box.

While there might be hacky css routes, but I want to keep my code clean. :) thanks.

**Comment by alioguzhan** [comment]
Sounds like a nice idea. But, what about `cancelling` ? We can call save method on mouse away. We still need a way to cancel modification. What do you think ?

**Comment by anz000** [comment]
We can listen for `Esc` buttons and perform cancellation based on that.

While I think cancellation button is more useful while shown, but if there's a way to remove all buttons, that'd be awesome.

**Comment by alioguzhan** [comment]
Hey @jdoklovic,
Do you have any idea or suggestion for this?

**Comment by alioguzhan** [comment]
> currently, I set the editButtonClassName to a custom css class that has:
> `visibility: hidden;`
> and set editOnViewClick to true.
> I think just adding a class for the save/cancel buttons to set visibility is common enough to remove them.

This sounds a proper way to achieve what you need. I wouldn't want to add more complexity and code if we can achieve it with the current feature set and some tweaks.

What do you think @anz000 ?

**Comment by alioguzhan** [comment]
I am closing this issue for now. Feel free to re-open if you find a different approach or have a suggestion.
