### ISSUE TITLE
Ways to update initial State without going into edit mode

### ISSUE THREAD

**Issue by sloyer** [alioguzhan/react-editext#42]
Hey everyone, 

First off let me say I love these fields they are making my life a breeze.
I am just running into an issue and maybe there is a solution out there and I am over looking it. 
But I have Values I need to pull from my backend (Firebase) and I would like my Edi Text fields to have these values in their initial state. 

Unfortunately, the fields show up blank, unless I toggle the edit button on then cancel. Then my value will appear.

If I edit the value and save the form, the value saves to the database fine and stays there, until I refresh where then the value will be blank again until I Trigger a state change.

**Describe the solution you'd like**
What I would like to happen is the value being pulled from my database be there without having to trigger the edit button. 

**Describe alternatives you've considered**
I've tried quite a few random things, the values will pull into a normal text box fine, so I am assuming it has something to do with how EdiText renders fields?

**Additional context**
I have attached some code below if you want to see how i am handling it thus far. 

But Ideally, I just want to say 
value={someValueFromDB}

```
/* eslint-disable camelcase */
import React, { Component } from 'react';
import _ from 'lodash';
import { Form, Button, Grid } from 'semantic-ui-react';
import EdiText from 'react-editext';
import { FileDragInput, TextInput } from '../../../components';
import Utils from '../../../helpers/Utils';

class Step1 extends Component {
  constructor(props) {
    super(props);
    this.state = {
      offerPurchacePrice: '',
      offerClosingCost: '',
      testingField: '',

      error: {},
    };

    this.fieldChange = this.fieldChange.bind(this);
    this.submit = this.submit.bind(this);
  }

  componentDidMount() {
    const {
      transaction_id,
      form,
      step,
    } = this.props;


    // Get all stored values.
    const formValues = Utils.LoadForm('SellerTransactions', transaction_id);

    // Once loaded merge current state with loaded values.
    formValues.then((results) => {
      const newState = _.merge({}, this.state, results.forms[form][step]);
      this.setState(newState);
    });
  }

  onSave = (val) => {
    console.log('Edited Value -> ', val);
  };

  fieldChange(name, value) {
    console.log(name);
    console.log(value);
    const obj = {
      [name]: value,
    };
    this.setState(obj);
  }

  submit() {
    const {
      save,
      // validate,
      form,
      step,
      transaction_id,
    } = this.props;

    // *************************
    // **** When validation is back uncomment below
    // *************************
    // const errors = validate(this.state, this.validators);
    // if (!_.isEmpty(errors)) {
    //   this.setState({ error: errors });
    // } else {
    //   save('SellerTransactions', transaction_id, form, step, this.state);
    // }
    // *************************
    // **** END
    // *************************

    // Temp, remove when above can be uncommented.
    save('SellerTransactions', transaction_id, form, step, this.state);
    console.log('saved');
    // console.log('---- state -----');
    // console.log(this.state);
    // console.log('---- end state -----');
  }

  render() {
    const {
      offerPurchacePrice,
      offerClosingCost,
      testingField,
      error,
    } = this.state;

    console.log('---- state -----');
    console.log(this.state);
    console.log('---- end state -----');

    return (
      <Grid.Row centered columns={5}>
        <Form color="green" onSubmit={this.submit}>
          <h1 className="ui centered">Offer Review</h1>

          <h2>Offer Details</h2>

          <TextInput
            name="testingField"
            label="Testing Field"
            type="text"
            component={TextInput}
            placeholder="Enter Testing Data"
            inputValue={testingField}
            onTextInputChange={this.fieldChange}
            error={_.has(error, 'testingField') ? error.testingField : false}
          />

          <EdiText
            mainContainerClassName="edi field-NotAccepted"
            type="text"
            onSave={value => this.fieldChange('offerPurchacePrice', value)}
            cancelButtonContent={<strong>Cancel</strong>}
            editButtonContent="Counter"
            value={offerPurchacePrice}
            // saveButtonClassName="custom-save-button"
            editButtonClassName="custom-edit-button"
            // cancelButtonClassName="custom-cancel-button"
            inputProps={{
              name: 'offerPurchacePrice',
              className: 'textarea',
              placeholder: 'Type your content here',

            }}
            hint="Don’t negotiate on the basis of asking price. Do negotiate on the basis of total cost of the transaction and total cost of owning the house."
          />

          <Button
            className="ui primary button"
            type="submit"
          >
            Submit
          </Button>
        </Form>
      </Grid.Row>
    );
  }
}

export default Step1;


```

**Comment by alioguzhan** [comment]
Hi,

Just to make sure, the `value` displayed on `view mode` is not being updated when you change the `value` prop that passed to `<EdiText/>` component.

this is the problem, right? If this is the case it shouldn't be like this way. The displayed content should be updated when the prop is changed. 

Can you create a `codesandbox` reproduces this issue?

Thanks.

**Comment by sloyer** [comment]
Thanks for getting back so fast!

Unfortunately, I can't make a sandbox for this but I can provide a demo of whats happening for a clearer understanding. 

https://youtu.be/3NTAt1J-b2c

The code is the same as above just has more fields to it. 

The ones with values showing are ones using the value Prop:

value="Enter Closing Cost"

The one with the value not showing is where we want to bring in a field from our Firebase Database and try and pass it like value={offerPurchasePrice}. 

Like how we do above with the normal input field above it. {testingfield}.

**Comment by alioguzhan** [comment]
Hey,

I will try to reproduce this on my local machine tomorrow. 

Until then, can you please try to pass a `key` prop to `EdiText` component? But not a static value. Something depends on firebase response. i.e `id`, `primary key` or some derived value from some text.

Thanks

**Comment by alioguzhan** [comment]
Hey, I tried to reproduce your issue. @sloyer 

I created a [sandbox](https://codesandbox.io/s/kind-cerf-jiben). Please check it. Here how it works:
- fetch some data from the server on `componentDidMount` and update the state.
- update the input by typing something.
- Click the save button and send the data to the server.
- Set the `EdiText`'s new value based on the server response.
It seems working. Can you please check it ? See the sandbox here:

[https://codesandbox.io/s/kind-cerf-jiben](https://codesandbox.io/s/kind-cerf-jiben)

Thanks

**Comment by sloyer** [comment]
Sorry for my slow reply on this! I have been traveling for work.

I will try this tomorrow and let you know!

**Comment by sloyer** [comment]
Hey there, 

So, I don't know if it's just a problem of conflict but I just can not get the input to update outside of the component. I made another video https://youtu.be/UD_eWGxfYgk

**Comment by alioguzhan** [comment]
It is weird. Seems like the same pattern that I created in Codesandbox, right? Can you create a demo app with `create-react-app` and include only `firebase` and `react-editext` and then try to reproduce the same issue?

**Comment by alioguzhan** [comment]
Hey @sloyer , I just released a new version which changes the way communication between props and state. Can you please update to the new version and try again?
