### ISSUE TITLE
Support password type

### ISSUE THREAD

**Issue by Coriou** [alioguzhan/react-editext#44]
Not sure if there's a reason not to support the password type, but I think that'd be great. It kinda works already, just throws a warning because `password` is not a valid prop.

**Comment by alioguzhan** [comment]
Hey,

You are right. I missed it. I can add `password` to the prop list and release a fix tonight. 

Also, feel free to send a PR.

Thanks

**Comment by alioguzhan** [comment]
Just release a new version with this fix. Please check it. I am closing the issue now. Feel free to re-open it.
Thanks.

**Comment by Coriou** [comment]
Hey man, sorry I've just seen you had replied. Thank you for the fix, I've tested it and it works as expected.
