### ISSUE TITLE
Submit on Enter key press

### ISSUE THREAD

**Issue by hnhegde** [alioguzhan/react-editext#46]
Hello,
While EdiText is a great component, it would be good to submit on Enter key press. If its possible already, would be great to include it in the examples. 

Thanks,
Harsha

**Comment by alioguzhan** [comment]
Hey, I just released a new version includes a new prop `submitOnEnter`. Can you please check it here:

https://alioguzhan.github.io/react-editext/#submit-on-enter

**Comment by hnhegde** [comment]
Hi @alioguzhan ,
Thanks for taking up my ask and making it available! Works great!
Regards,
Harsha

**Comment by bo0tzz** [comment]
Hi,
This feature is awesome, however when the EdiText field is used inside a <form>, pressing enter submits the whole form. Would it be possible to prevent this, for example by binding the keypress event listener to the field instead of to window, and calling event.preventDefault()?
