### ISSUE TITLE
Display line breaks when using <textarea>

### ISSUE THREAD

**Issue by YaoRenaudWoana** [alioguzhan/react-editext#48]
**Problem**
The line breaks are not displayed when using <textarea>

**Other**
it would be a good idea to remove trailing and leading spaces too.

**Comment by alioguzhan** [comment]
Hey, thanks for the issue. By saying `The line breaks are not displayed` do you mean it displays multiline texts as one line when it passed as `value`? 

Also, you can reproduce this template:

 https://codesandbox.io/s/react-editext-template-5twrh

Thanks

**Comment by YaoRenaudWoana** [comment]
Yeah I mean multiline texts are displayed as one line text.

Reproduced here : https://codesandbox.io/s/react-editext-template-ew8w5

**Comment by alioguzhan** [comment]
The above URL is not changed. I think you forgot to save it. Can you check it.

**Comment by YaoRenaudWoana** [comment]
Done

**Comment by alioguzhan** [comment]
Hey. We can solve this by adding a css rule to the `viewProps`. Can you please check this:

https://codesandbox.io/s/react-editext-template-o4do5

Is this what you need ? I will think about making this solution default behavior.

**Comment by YaoRenaudWoana** [comment]
Yes it's good.
