### ISSUE TITLE
Styled Components or Emotion to Enhance Styling

### ISSUE THREAD

**Issue by justinkuntz** [alioguzhan/react-editext#52]
We are using EdiText in an app that utilizes styled-components. I am trying to style items like the buttons for Edit, Cancel, and Save but am having little luck. 

It would be great to build out a styled component that we could just drop in that comes with our styled elements. For example build out the styled-component:

```
const InlineEdit = styled(EdiText)`
  button { 
    border: red;
  }
  input {
    background: transparent;
  }
  .assigned-className {
    color: white;
  }
`;
```

```
<InlineEdit 
  showButtonsOnHover
  submitOnEnter
  hideIcons="true"
  editButtonContent=<BorderColor size="16" /> (<-- Material icons as styled components actually works)
  saveButtonContent=<Check size="16" />
  cancelButtonContent=<Close size="16" />
  type="text"
  value="Edit Me"
  onSave={this.onSave} 
/>
```

I have tried to style with some of the `inputProps` and `viewProps` with inline styles but can't target the details. Perhaps even an outline of the output structure would help. What is the best way to target the button elements for Edit/Save/Cancel?

**Comment by alioguzhan** [comment]
Hey Justin, 

I think I understand what you are trying to achieve. You want to style the `EdiText` by targeting internal HTML elements. 

I never thought of this while building the component. Give me a day or so and I will see what we can do. Sounds good to you?

**Comment by justinkuntz** [comment]
Awesome thanks @alioguzhan

**Comment by alioguzhan** [comment]
Hey Justin,

https://github.com/alioguzhan/react-editext#styling-with-styled-components

Can you please first read this section in README and then click to the bottom link to navigate to the examples page?

I need a review/feedback before sending a new release to the NPM. 

You can even test this version on your local / codesandbox by settings repository URL in package.json.

Please let me know. 

Thanks.

**Comment by justinkuntz** [comment]
@alioguzhan apologies for not reviewing sooner. I pulled it locally and everything seems to work. I made some changes in the Examples directory and I could target everything I needed to style. For whatever reason `npm install` would not work on that directory, I had to use yarn and `yarn start`.

Nice work and thank you for tackling this so quickly!

**Comment by alioguzhan** [comment]
Great! 

I just sent a new release to the NPM. Feel free to open an issue again if you find anything broken. 

Thanks for the feedback!

**Comment by alioguzhan** [comment]
@all-contributors please add @justinkuntz for ideas and bug.
