### ISSUE TITLE
Get name of EdiText on save

### ISSUE THREAD

**Issue by soncco** [alioguzhan/react-editext#57]
I have several EdiText components and I want to save each data separately.

Example:
````
        <EdiText
            type="text"
            value='fooValue'
            inputProps={{
                name: 'foo'
            }}
            onSave={this.onSave}
            />

        <EdiText
            type="text"
            value='barValue'
            inputProps={{
                name: 'bar'
            }}
            onSave={this.onSave}
            />
````

And the onSave function will receive:

````
onSave = (val, name) => {
  // Code for save val for the specified name only. 
}
````

Or how can we get the name of the input that has triggered the onSave callback?

**Comment by alioguzhan** [comment]
Hey,

What about if we pass the whole `inputProps` as the second argument to the `onSave` callback?
```js
onSave = (val, inputProps) => {
}
```
We can use `id` or `name` or any other attribute to distinguish multiple EdiText's from each other. 

What do you think ?

**Comment by soncco** [comment]
It's a good idea!!!

**Comment by alioguzhan** [comment]
@all-contributors please add @soncco for idea and feedback.
