### ISSUE TITLE
pressing escape has same effect as enter

### ISSUE THREAD

**Issue by zig** [alioguzhan/react-editext#60]
with submitOnEnter, when pressing escape, it calls onSave instead of onCancel

**Comment by alioguzhan** [comment]
Hey, @zig thanks for this!

I just released a new version fixes this. Can you please verify if it is working :

https://alioguzhan.github.io/react-editext/#submit-on-enter

@all-contributors please add @zig for bug report

**Comment by zig** [comment]
Thank you, it does indeed not call onSave anymore, now it would be perfect if it called onCancel :)

**Comment by zig** [comment]
Another remark : I first tested by updating the package through npm, I got release 3.12.2 which should contain the fix, but it doesn't seem to. So I actually applied your fix manually to test.
Am I doing a mistake somewhere ? I don't see it.

**Comment by alioguzhan** [comment]
> Thank you, it does indeed not call onSave anymore, now it would be perfect if it called onCancel :)

I am not sure if assigning new handlers to the user's keyboard without asking them :) Since the prop's name is `submitOnEnter` let's limit its scope only with `Enter`. If you want to add extra handlers you can use `onKeyDown` via the `inputProps`. What do you think?



> Another remark : I first tested by updating the package through npm, I got release 3.12.2 which should contain the fix, but it doesn't seem to. So I actually applied your fix manually to test.
> Am I doing a mistake somewhere ? I don't see it.

Ah! That's my mistake. I will send a new release :/ Thanks for this!

**Comment by alioguzhan** [comment]
Just released a new version `3.12.4`. Can you please check? Thanks. @zig

**Comment by zig** [comment]
> I am not sure if assigning new handlers to the user's keyboard without asking them :) Since the prop's name is `submitOnEnter` let's limit its scope only with `Enter`. If you want to add extra handlers you can use `onKeyDown` via the `inputProps`. What do you think?

I see, I hadn't noticed we could customize onKeyDown, I am OK with this solution, though I'd say having a `cancelOnEscape` option might be a bit more user friendly (but I am nitpicking :)

**Comment by zig** [comment]
> Just released a new version `3.12.4`. Can you please check? Thanks. @zig

Seems good, thanks !

**Comment by alioguzhan** [comment]
> > I am not sure if assigning new handlers to the user's keyboard without asking them :) Since the prop's name is `submitOnEnter` let's limit its scope only with `Enter`. If you want to add extra handlers you can use `onKeyDown` via the `inputProps`. What do you think?
> 
> I see, I hadn't noticed we could customize onKeyDown, I am OK with this solution, though I'd say having a `cancelOnEscape` option might be a bit more user friendly (but I am nitpicking :)

That makes sense actually :) I can implement it in a few days or so. I will let you know! :)

Feel free to close this issue.
