### ISSUE TITLE
Feature Request: Cancel on unfocus

### ISSUE THREAD

**Issue by isaiahtaylor** [alioguzhan/react-editext#74]
**Is your feature request related to a problem? Please describe.**
A predictable pattern for inline-editability is to cancel the editing session when the user "clicks away." 

**Describe the solution you'd like**
Optional prop like "cancelOnUnfocused" that cancels the editing when the component loses focus.

Thanks so much for a great library!

**Comment by alioguzhan** [comment]
Hey, thanks for the suggestion! 

It sounds like a great idea. 

I will let you know once it is completed. 👍

**Comment by alioguzhan** [comment]
@all-contributors please add @isaiahtaylor for ideas.
