### ISSUE TITLE
Feature Request: Save on unfocus (saveOnUnfocus)

### ISSUE THREAD

**Issue by anz000** [alioguzhan/react-editext#79]
**Is your feature request related to a problem? Please describe.**
User starts typing in. They never click the Save or press Enter. 
The user are under the assumption that the updated text got saved, but it never did.

**Describe the solution you'd like**
on UnFocus (or mouse away), call the onSave handler. (very similar to cancelOnUnfocus but it saves instead)

**Describe alternatives you've considered**
I tried adding handler, but could not get it to work.

**Comment by alioguzhan** [comment]
Hey, 

can you please check #80 and the [example code at deploy preview page](https://deploy-preview-80--react-editext.netlify.com/#submit-on-blur)

Tell me what you think, please.

**Comment by anz000** [comment]
Looks great, exactly what I was hoping for.

**Comment by alioguzhan** [comment]
@all-contributors please add @anz000 for ideas.
