### ISSUE TITLE
Option to set className for the text div

### ISSUE THREAD

**Issue by yehudaTiram** [alioguzhan/react-editext#8]
Hey, it is a good component, thanks.
There's no way to directly control the the value element `<div>text</div>` with css.
in the 
`<div class="styles_Editext__main_container__2Y-IL"><div class="styles_Editext__view_container__2l2kB"><div>text</div><div class="styles_Editext__buttons_container__1kphL"><button type="button" class="styles_Editext__button__6H8n_ styles_Editext__edit_button__hthOZ"></button></div></div></div>`

When I add a custom className like 
`<EdiText className="edit-text-full-width" type="text" value='text' onSave={this.onSave} />`
it is ignored.
Any chance to do something with this?

**Comment by alioguzhan** [comment]
Hey!

You can use `viewProps` to styling and other stuff. anything you passed with `viewProps` will be passed to text div. And there is also `inputProps` to pass any prop to the input element. 

Please see the `Custom Props for Text Element` section in [Example Page](https://alioguzhan.github.io/react-editext/)

**Comment by yehudaTiram** [comment]
Thanks for the quick pointer Ali, 
I missed that.
Tried it now and it works very nice.

**Comment by alioguzhan** [comment]
@all-contributors please add @yehudaTiram for question
