### ISSUE TITLE
Clicking the "save" button too soon after typing doesn't save

### ISSUE THREAD

**Issue by Chryogenic** [alioguzhan/react-editext#82]
**Describe the bug**
When typing and then immediately trying to click the save button, it isn't registering the click. I have to wait a couple seconds then try clicking again.

**Expected behavior**
At anytime the save button is clicked, the input should immediately be saved.

**Steps to reproduce**
CodeSandbox Example: **https://codesandbox.io/s/react-editext-template-5twrh**  

1. Open the editext control to edit mode.
2. Start typing random letters
3. (while still typing) Click on the save button
4. Stop typing and click on the save button
5. Notice that it takes a couple seconds before it will save

**Comment by alioguzhan** [comment]
Hey, I couldn't reproduce the issue. It seems fast to me. 

- The sandbox you shared is using an old version of the `react-editext`. Can you please use the latest version?
- Do you see the same slowness on the [example page](https://alioguzhan.github.io/react-editext/)?


Thanks.

**Comment by Chryogenic** [comment]
Hi @alioguzhan,

It appears this issue is local to my setup. I experience this issue when using my laptop with a usbc hub with my mouse and keyboard connected through the hub.

When using the laptop mouse and keyboard directly, the issue is gone.

Thanks for all your work on this project and sorry for the false alarm :)
