### ISSUE TITLE
Allow for tab and keyboard editing

### ISSUE THREAD

**Issue by amirmishani** [alioguzhan/react-editext#86]
**Is your feature request related to a problem? Please describe.**
I'm using react-editext inside an editable table. I want to be able to tab through each table cell and edit them using keyboard only. I'm also hiding all buttons and only relying on `submitOnEnter`, `submitOnUnfocus`, and `editOnViewClick` to edit and save. However as things are now I have to use a mouse to click into a cell to make it editable, the new feature being requested will allow a user to tab into each view and either by hitting enter on the keyboard or simply by the view being in focus switch to input.

**Describe the solution you'd like**
First a `tabIndex` prop that is passed to both viewProps and inputProps. I'm currently adding it twice through the input and view props like so:

```javascript
<EditText
   inputProps={{
       tabIndex: 0,
   }}
   viewProps={{
      tabIndex: 0,
   }}
/>
```
instead it would be great if I could just pass it once through the main props
```javascript
<EditText
  tabIndex={0}
/>
```

Second, I'd like to see two more props added. Both will accomplish the same results so I expect the developers using one or the other depending on their need: 

1. `editOnViewEnter` similar to `editOnViewClick` but it works via keyboard enter rather than mouse click. This would require the element to be in focus which is why adding the previous tabIndex is important.

2. `editOnViewFocus` this is similar to the previous props but this time as soon as you focus on the view it switches to edit mode. 

so the new props would looks like:
```javascript
<EditText
   tabIndex={0}
   editOnViewEnter /* or */ editOnViewFocus
   submitOnEnter
   submitOnUnfocus
   editOnViewClick
/>
```

**Additional context**
Being able to tab through a form or a table and edit  quickly via keyboard can really elevate the user experience for any app. So I think this would be a great addition to this wonderful package. Thank you.

**Comment by alioguzhan** [comment]
Hey, thanks for the issue. 

> instead it would be great if I could just pass it once through the main props

The reason why I separated the `inputProps` and `viewProps` is because people will want to assign props to both elements. There are also `EdiText-specific` props like `submitOnEnter` which can be passed to neither `input` nor `view` element. That's why we have `inputProps` and `viewProps`. I couldn't think of any solution other than this. But I am open to suggestions!

> `editOnViewEnter` similar to `editOnViewClick` but it works via keyboard enter rather than mouse click. This would require the element to be in focus which is why adding the previous tabIndex is important.

> `editOnViewFocus` this is similar to the previous props but this time as soon as you focus on the view it switches to edit mode.

That makes sense. I will try to implement this and will let you know! Feel free to say if you have additional comments/ideas!

Thanks!

**Comment by amirmishani** [comment]
@alioguzhan I definitely think `inputProps` and `viewProps` are necessary and they're very useful. I didn't mean to change them in any way, I should have been more clear, I just meant adding the new `tabIndex ` which will trickle down to both input and view.

**Comment by alioguzhan** [comment]
Ah! I see now. Yes, passing down the `tabIndex` to both props makes sense. I will mention you once I create a PR for this!

**Comment by alioguzhan** [comment]
Just sent a new version to the npm. Please check it!

**Comment by alioguzhan** [comment]
@all-contributors please add @amirmishani for features

**Comment by alioguzhan** [comment]
@all-contributors please add @amirmishani for ideas
