### ISSUE TITLE
Detect change in value as I type/erase

### ISSUE THREAD

**Issue by anz000** [alioguzhan/react-editext#94]
**Is your feature request related to a problem? Please describe.**
How can I add a onChange listener everytime I add or delete text?

**Describe the solution you'd like**
I'd like to be able to detect the change in the value, and process that change without saving.
Something like , `onValueUpdated`.

I tried adding `onKeyPress` and `onChange` to `inputProps` like:
```
inputProps={{
 placeholder: 'Search...',           // placeholder
 onKeyPress: () => console.log("Key Press"),
}}
```
The keypress gets detected when I type in a new character, but not when i delete some characters

**Comment by anz000** [comment]
This works.

```
inputProps={{
 placeholder: 'Search...',
 onKeyDown: () => console.log("Key Press"),
}}
```
Initially, I tried "onKeyPress" and apparently it only detects printable character. So, "onKeyDown" seems to be the way to go. 

It would be great if this could be added to the documentation. Thanks.

**Comment by anz000** [comment]
I ended up adding a `ref` to the `Editext` element and access the value that way.
```
<EdiText
 ref={elm => {this.searchElm = elm}}
 ...
```
`this.searchElm.state.value` has the current value for the element. Wonder if there is a better way, otherwise this issue can be closed.

**Comment by alioguzhan** [comment]
Hey @anz000 , thanks for the issue. I am trying to avoid more props/features to this version of the component. If a request can be achieved with the current structure, my vote is to NOT implement it. There are already too many props. What do you think?

**Comment by anz000** [comment]
Sounds good, @alioguzhan .

**Comment by spostad7** [comment]
Solved by using inputProps
Thanks
