### ISSUE TITLE
Question: is it possible to hide the icons...?

### ISSUE THREAD

**Issue by jamiebullock** [alioguzhan/react-editext#95]
Hi, great work with EditText!

Is there any straightforward way to hide all the icons...? 

I would like: 

- Click or focus to edit
- Enter to submit
- Escape to cancel

All of this is already possible, but I would like to hide the icons.

**Comment by alioguzhan** [comment]
Hey!

There is a 'hideIcons' prop. Is this what you need?

**Comment by jamiebullock** [comment]
Sorry, my request wasn't clear. I want to hide the buttons altogether, not just the icons.

**Comment by alioguzhan** [comment]
Ah, There is no any direct prop to achieve this, but you can hide any element by using `styled-components`. 

You can target and apply styles almost any part of the editext component. Or you can achieve the same thing by using classname props. 

https://github.com/alioguzhan/react-editext#styling-with-styled-components

`saveButtonClassName`
`editButtonClassName`
`cancelButtonClassName`

https://github.com/alioguzhan/react-editext#styling-with-styled-components

Do you think this will help you to solve your problem?

**Comment by jamiebullock** [comment]
@alioguzhan thanks for the quick reply! Yes, this solves my problem.
